# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95a79d9fe6ee8f2a15791d83e71b3aa57778de77c711e7403312df38864c3723e0c69d0d3733d87c6c180ac59743bcd5899c9643431bb0121809cefd944453ec

test:
  secret_key_base: 7d27c0f3deecbdb78d59affd0dfa20dea6129c543c114d481207c478415b0ff087aec2b1f060f42cfdd5c3f04fb6174576edce41ca0064fddf8f46d7e1dfcdb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
